namespace LegacyEngine.Relationships;

public enum RelationshipType
{
    Professional,
    OwnerToGM,
    GMToOwner,
    GMToScout,
    ScoutToGM,
    GMToPlayer,
    PlayerToGM,
    GMToStaff,
    StaffToGM,
    GMToAgent,
    AgentToOrganization,
    OrganizationToAgent,
    OrganizationToPlayer,
    PlayerToOrganization,
    OrganizationToStaff,
    StaffToOrganization,
    OrganizationToOrganization,
    StaffToStaff,
    StaffToOwner,
    OwnerToStaff,
    PlayerToStaff,
    StaffToPlayer,
    CoachToPlayer,
    PlayerToCoach,
    PlayerToPlayer,
    ParentToOrganization,
    AgentToGM,
    Mentor,
    Family,
    Media,
    League,
    Unknown
}
