namespace LegacyEngine.Events;

public enum LegacyEventType
{
    PersonCreated,
    RoleStarted,
    RoleEnded,
    RelationshipChanged,
    OwnerGoalSet,
    BudgetApproved,
    ScoutAssigned,
    ScoutingReportCreated,
    RuleValidationFailed,
    RecruitingOfferSubmitted,
    RecruitCommitted,
    RecruitRejected,
    ContractOffered,
    ContractSigned,
    ContractRejected,
    ContractTerminated,
    PlayerInjured,
    DraftStarted,
    PlayerDrafted,
    DraftCompleted,
    PlayerAddedToRoster,
    PlayerRemovedFromRoster,
    PlayerMovedToInjuredReserve,
    PlayerReleased,
    PlayerDevelopmentUpdated,
    PlayerBreakout,
    PlayerRegression,
    GamePlayed,
    SeasonStarted,
    SeasonEnded,
    Generic
}
