namespace LegacyEngine.Integration;

public enum LeagueTransactionType
{
    PlayerSigned,
    ContractOffered,
    ContractSigned,
    PlayerAddedToRoster,
    PlayerReleased,
    PlayerAssigned,
    PlayerRecalled,
    WaiverPlaced,
    WaiverClaimed,
    WaiverCleared,
    RfaQualified,
    RfaNotQualified,
    PlayerBecameUfa,
    RightsReleased,
    ArbitrationFiled,
    ArbitrationAwardIssued,
    ArbitrationSettled,
    ArbitrationWalkAway,
    ContractBoughtOut,
    Injury,
    DraftPick,
    StaffHired,
    StaffReleased,
    TradeCompleted,
    TradeDeadline,
    SeasonCompleted,
    TeamIdentityUpdate,
    PlayerMilestone,
    StaffMilestone,
    OwnerMilestone,
    StoryUpdate
}
